const List<String> motivationalQuotes = [
  'Success is not final, failure is not fatal. It is the courage to continue that counts.',
  'The only way to do great work is to love what you do.',
  'Believe you can and you are halfway there.',
  'Start your day with fully energy and make it count!',
  'Every accomplishment starts with the decision to try.',
  'Your potential is endless. Go do what you were created to do.',
  'The future depends on what you do today.',
  'Don\'t watch the clock; do what it does. Keep going.',
  'Hard work beats talent when talent doesn\'t work hard.',
  'Push yourself, because no one else is going to do it for you.',
  'Great things never come from comfort zones.',
  'Dream it. Wish it. Do it.',
  'Stay focused, go after your dreams and keep moving toward your goals.',
  'Success doesn\'t just find you. You have to go out and get it.',
  'The harder you work for something, the greater you\'ll feel when you achieve it.',
  'Wake up with determination. Go to bed with satisfaction.',
  'Do something today that your future self will thank you for.',
  'Little things make big days.',
  'It\'s going to be hard, but hard does not mean impossible.',
  'Work hard in silence, let your success be the noise.',
];
